"""catalog resource types table

Revision ID: 2b8ca93d5b89
Revises: 643934c1e272
Create Date: 2026-04-25 20:47:48.968708

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '2b8ca93d5b89'
down_revision: Union[str, None] = '643934c1e272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_types',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('attribute_schema', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_types_is_active'), 'resource_types', ['is_active'], unique=False)
    op.create_index(op.f('ix_resource_types_slug'), 'resource_types', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_types_slug'), table_name='resource_types')
    op.drop_index(op.f('ix_resource_types_is_active'), table_name='resource_types')
    op.drop_table('resource_types')
    # ### end Alembic commands ###
