from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime, timezone
from uuid import UUID, uuid4


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


@dataclass(slots=True, kw_only=True, eq=False)
class BaseEntity:
    id: UUID = field(default_factory=uuid4)
    created_at: datetime = field(default_factory=_utcnow)
    updated_at: datetime = field(default_factory=_utcnow)

    def __eq__(self, other: object) -> bool:
        return isinstance(other, BaseEntity) and self.id == other.id

    def __hash__(self) -> int:
        return hash(self.id)

    def __init_subclass__(cls, **kwargs: object) -> None:
        object.__init_subclass__(**kwargs)
        # Ensure subclasses generated by @dataclass(eq=True) do not override
        # the identity-by-id semantics defined here.
        cls.__eq__ = BaseEntity.__eq__  # type: ignore[method-assign]
        cls.__hash__ = BaseEntity.__hash__  # type: ignore[method-assign]
