from __future__ import annotations
from typing import Protocol, Sequence
from uuid import UUID
from app.domain.accounts.user import User


class IUserRepository(Protocol):
    async def get_by_id(self, user_id: UUID) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def list_active(
        self, *, limit: int = 50, offset: int = 0
    ) -> Sequence[User]: ...
    async def add(self, user: User) -> None: ...
    async def update(self, user: User) -> None: ...
